### ISSUE TITLE
Add ForceSub to Private Channel and the request will not be auto Accepted 👍

### ISSUE THREAD

**Issue by itzmadara** [zawsq/Teleshare#2]
**Is your feature request related to a problem? Please describe.**
An option to make request invitation for private channels

**Describe the solution you'd like**
Allows private usage of bots

**Comment by zawsq** [comment]
Added this on: https://github.com/zawsq/Teleshare/commit/d59854655b220b80e0272f83d0619d987bc3e62f

Just add:
`PRIVATE_REQUEST = True`
on your .env or environment to enable.
