### ISSUE TITLE
New function.

### ISSUE THREAD

**Issue by techwha** [zawsq/Teleshare#22]
### Describe the feature

Add a button for the user to “try again” after they enter the channel, the bot will send the file.
![IMG_20240517_220146](https://github.com/zawsq/Teleshare/assets/132772813/e6a153da-ad17-413a-b469-d9425ee877b9)

**Comment by zawsq** [comment]
Added on: https://github.com/zawsq/Teleshare/commit/4c34ebb8f8b84d7a6c3e6b25094766e46304fd83

Wait for it to get merged on main or use mvp-stage branch
