### ISSUE TITLE
Function suggestion

### ISSUE THREAD

**Issue by techwha** [zawsq/Teleshare#27]
### Describe the feature

Add an option to put whatever text you want on the force sub buttons, currently the bot shows the channel name, a way to change it to anything would be good. 
![IMG_20240523_160635_872](https://github.com/zawsq/Teleshare/assets/132772813/aeafe6d9-9cd5-44aa-938f-f8a48084abea)

**Comment by zawsq** [comment]
Currently won't put this on mandatory features, but something we can add in the future. Invite button for channel and group invites are automatically generated on startup.

**Comment by zawsq** [comment]
Closing this for the time being, as it is not planned. Group/channel invite links are directly generated during bot startup.
