### ISSUE TITLE
user points system

### ISSUE THREAD

**Issue by garyvalue** [zawsq/Teleshare#49]
### Describe the feature

May I ask if we are considering a user points system? Only when the user has sufficient points can they obtain the file.
If there is any intention in this regard, I will provide more ideas.

**Comment by zawsq** [comment]
Hello, i plan to keep the bot minimal as much as possible, would be better if you add more context on how a user could possibly gain those "points".

**Comment by garyvalue** [comment]
In my opinion, the purpose of the points system is to facilitate more users to share their files, like a hub for exchange.

User A uploads a file and sets a point. When the value of the file is determined to match this point, User A will receive points.
For example, user A uploaded a course video and set it to 5 points (preferably with a file introduction). When the value of the course video is determined to meet this point, user A will receive 5 points.
If user B wants to obtain this file, they need to first upload their own file to earn points. Having enough points is necessary to obtain the file uploaded by user A.

We can set up a public channel to announce which files users have uploaded and promote their use of robots.
