### ISSUE TITLE
/batch (improvement)

### ISSUE THREAD

**Issue by ITZ-HERO-TIME** [zawsq/Teleshare#52]
### Describe the feature

Dear Dev. Make like when we create batch file , we have to send all file to our (FILE LOG) chnl and then for batch we have to give only first and last file chat link

**Comment by zawsq** [comment]
This changes should be an alternative for now: https://github.com/zawsq/Teleshare/pull/58/commits/9382f9d282a9e658c1a7e0ce16f08cc40e9ce0d3

It should allow you to forward many files during /make_files conversation without a problem.

**Comment by zawsq** [comment]
/range_files command added on: https://github.com/zawsq/Teleshare/commit/8833846129f1c4be9d4de27d29738f96e79b06ae
