### ISSUE TITLE
Add point system invite bot

### ISSUE THREAD

**Issue by actchanthar** [zawsq/Teleshare#55]
### Describe the feature

And who have referred bot

I mean point system in teleshare bot

Who invited link 

bot?start=invite12345

They will get some points 50point per invite bot

And bot get many users then they want to invite

**Comment by zawsq** [comment]
This is similar to: https://github.com/zawsq/Teleshare/issues/49

**Comment by garyvalue** [comment]
> This is similar to: #49这类似于： #49

Can this feature be used as a branch project?

**Comment by zawsq** [comment]
No plan implementing. Just keeping the project minimal.
