### ISSUE TITLE
Command delete_link not working!

### ISSUE THREAD

**Issue by farp0** [zawsq/Teleshare#76]
### Describe the feature

Hi, The /delete_link command does not work properly. And it does not delete any link, only this message is displayed
Cannot find link: Either it has been deleted or it does not exist.

Please check.

![IMG_20241114_155152_857](https://github.com/user-attachments/assets/08b5b7a8-66c7-47ed-aa05-7c5c853a0ecc)

**Comment by zawsq** [comment]
Fixed at: https://github.com/zawsq/Teleshare/pull/77
